In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import spacy
nlp = spacy.load('en_core_web_sm')

In [11]:
dat = nlp('A')
print(f'{dat.vector}\n{len(dat.vector)}')


[-0.20826823  0.12713754 -0.14263934  1.1650069   1.2930927  -0.3983816
 -0.5352546   0.3872813   0.72502357 -0.6226468   0.64545226 -0.70988876
 -1.1074061  -0.4201635  -0.9371325  -0.43676117  0.5733069   0.41179922
 -0.0127802  -0.58860296  0.2698432  -1.0604827  -0.8847261  -0.06006956
  0.08650735 -0.18327478 -0.23889358 -0.10295721  0.72665465 -0.23190081
 -0.7737855  -0.3886688   0.2904046  -0.40439108  0.51155     0.97137374
 -1.3611116   0.11782441  0.3282594   0.61154664 -0.19737552  0.24975805
  0.55673164  0.5538432  -0.25528058 -0.4939462   0.11661762  0.5558151
 -0.44960672  1.0128268   0.8394635  -0.54120183 -0.61795807  1.1383634
 -0.72546196 -0.7288139  -0.6248926   0.62615514 -0.8837294   0.5226747
  0.03490335  0.21204871 -0.39613765  1.0421399  -0.12418401 -0.5842167
 -0.37850216 -0.9133986   0.21557528  0.5828844   1.1845528  -0.09978118
  0.51616246  0.6842251  -0.6670178  -0.37937295 -0.6594833  -0.68303305
 -0.52337873 -1.467248    0.0858167   0.26277143 -0.4562

In [15]:
dat = nlp('Lion')
print(f'{dat.vector}\n{len(dat.vector)}')

[-0.60007215 -0.94713926  0.04873745  0.05487522  0.55116713 -0.719188
 -1.0815502  -0.30971614 -0.7965381  -0.5065464   1.0088444  -0.7585948
  0.24714893  0.22302401 -0.82629657 -0.18199344  0.61294496 -0.3108295
 -0.2768529  -0.7613095   0.01372528 -0.89081615 -0.5152591  -0.14704642
 -0.15926145 -0.15585268  0.69180477 -0.41836852  0.5830106  -0.34502774
 -0.00822601  0.5870524   0.02609217 -0.78245145  0.9072466   0.42838365
 -1.1260165   0.5669892   0.5480763   0.18929742 -0.2689569   0.6889051
 -0.45764324  1.4620233   0.3987195   0.04610081  0.5734613  -0.07016495
 -0.41352084 -0.09570777  0.4444854  -0.02192254  0.29810986  0.22920638
  0.07089186 -0.20197743  0.40635934  0.21789041 -0.03928068 -1.2361307
  0.85226643 -0.52225494  0.02510372 -0.26303402 -0.34535596 -0.7236579
 -0.9247444  -0.19167972 -0.07182872  0.71157837  0.10427317 -0.6788765
  0.1770151  -0.58109283  0.2306233   1.2075067   1.0788438  -1.141295
 -0.35832554  0.3545314   0.02254666  0.11084317  0.22811207 

In [16]:
dat = nlp('Lion cat dog')
print(f'{dat.vector}\n{len(dat.vector)}')

[ 0.53267145  0.10796853  0.45326853  0.2363503   0.5919409  -0.93883705
 -0.771748    0.6134777  -0.44713512 -0.07784637  0.92253286 -0.26691428
 -0.28200784 -0.547226   -0.66178596  0.10567981  0.09956113  0.5210771
 -0.64037997  0.00244359 -0.54846704  0.12491261 -0.48511776 -0.5303642
  0.42132565 -0.35830465  0.56586623 -0.42213628  0.24620356 -0.27941254
 -0.31015968  0.11534787 -0.18370725 -0.40889367  0.31130856 -0.2968854
 -0.84854144  0.9994547   0.5552049   0.38284215 -0.17024906 -0.09062407
 -0.6949633   0.43542108  0.29622784  0.15244263  0.12579429  0.37979588
 -0.21999077 -0.01502666  0.720542   -0.4062856  -0.23428257 -0.239213
 -0.05065138 -0.22544463  0.05992271 -0.14580017 -0.00471025  0.28926155
  0.1268905  -0.22198956  0.12207869 -0.8595505  -0.5731012  -0.23891382
 -0.9867013   0.6126359  -0.05912578  0.25514346  0.03329756  0.49324727
 -0.10152629 -0.030743    0.3008788   1.0809989  -0.08646282 -0.39549872
 -0.473749    0.3057629   0.20321864  0.13110264 -0.2479

In [19]:
dat = nlp('irgf grihgekjG jrghekgb brjhbbfh gbhghjrb rhg.')
print(f'{dat.vector}\n{len(dat.vector)}')

[-0.11298064 -0.70101136  0.02219179  0.3887036  -0.16247189 -0.8906938
 -0.4478125   0.18281099 -0.18755926  0.13273947  0.9157933   0.30093437
 -0.20484829 -0.23078407 -0.17696132 -0.20183925 -0.2097921   0.19489945
 -0.5720296   0.2307633  -0.32711047 -0.31566468 -0.11946907 -0.6345553
  0.4964212  -0.5721558   0.16278307 -0.41903237  0.3956044   0.09421104
  1.2175974   0.8232731   0.13150184  0.1511226  -0.04520465  0.04397935
 -0.37924096  1.4098654  -0.29130957 -0.3207681   0.53740036  0.54116935
 -0.00376712  0.22274564  0.4481294  -0.39170042  0.48946506 -0.6639232
 -0.8870982  -0.5721799   0.5179302  -0.23496416  0.14354065 -0.42169985
 -0.08694977 -0.06984724  0.28336495  0.42841926 -0.043628    0.10904248
  0.95383084 -0.16471402  0.62243015 -0.15449126  0.03384773 -0.00481003
 -0.62537974 -0.48991156 -0.10940082 -0.28784326  0.37731475  0.51578146
 -0.46545342 -0.8035985   0.1550118   0.06400039  0.5670532   0.21996768
 -0.30865544  0.09495772  0.32756037 -0.06857301  0.19

In [21]:
tokens = nlp('lion cat dog table')
for token1 in tokens:
    for token2 in tokens:
        print(token1.text,token2.text,token1.similarity(token2))

lion lion 1.0
lion cat 0.5468022
lion dog 0.55252165
lion table 0.21396983
cat lion 0.5468022
cat cat 1.0
cat dog 0.6610272
cat table 0.18251853
dog lion 0.55252165
dog cat 0.6610272
dog dog 1.0
dog table 0.256253
table lion 0.21396983
table cat 0.18251853
table dog 0.256253
table table 1.0


<ipython-input-21-0ce15ba2a55f>:4: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Token.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print(token1.text,token2.text,token1.similarity(token2))


In [22]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\subha\AppData\Roaming\nltk_data...


True

In [24]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [25]:
sia = SentimentIntensityAnalyzer()

In [26]:
txt = 'My favourite book was lying somewhere.'
sia.polarity_scores(txt)

{'neg': 0.405, 'neu': 0.595, 'pos': 0.0, 'compound': -0.5267}

In [28]:
txt = ('This was One of the best movies.')
sia.polarity_scores(txt)

{'neg': 0.0, 'neu': 0.588, 'pos': 0.412, 'compound': 0.6369}

In [29]:
txt = ('This movie was watchable.')
sia.polarity_scores(txt)

{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}

In [31]:
txt = ('This movie was bad.')
sia.polarity_scores(txt)

{'neg': 0.538, 'neu': 0.462, 'pos': 0.0, 'compound': -0.5423}

In [33]:
txt = ('Awesome food')
sia.polarity_scores(txt)

{'neg': 0.0, 'neu': 0.196, 'pos': 0.804, 'compound': 0.6249}

#  Sentiment analysis

In [34]:
data = pd.read_csv('amazonreviews.tsv',sep='\t')
data.head()

label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [35]:
data.describe()

label                                             review
count   10000                                              10000
unique      2                                              10000
top       neg  Asvab for Dummies: It was a good book but the ...
freq     5097                                                  1

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   label   10000 non-null  object
 1   review  10000 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB


In [43]:
data.label.value_counts()

neg    5097
pos    4903
Name: label, dtype: int64

In [55]:
print(data.iloc[4,1])
print(sia.polarity_scores(data.iloc[4,1]))

Remember, Pull Your Jaw Off The Floor After Hearing it: If you've played the game, you know how divine the music is! Every single song tells a story of the game, it's that good! The greatest songs are without a doubt, Chrono Cross: Time's Scar, Magical Dreamers: The Wind, The Stars, and the Sea and Radical Dreamers: Unstolen Jewel. (Translation varies) This music is perfect if you ask me, the best it can be. Yasunori Mitsuda just poured his heart on and wrote it down on paper.
{'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'compound': 0.9781}


In [57]:
data['scores'] = data['review'].apply(lambda x: sia.polarity_scores(x))
data.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...

In [62]:
data['compund'] = data['scores'].apply(lambda x:x['compound'])
data.head(10)

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   
5   pos  an absolute masterpiece: I am quite sure any o...   
6   neg  Buyer beware: This is a self-published book, a...   
7   pos  Glorious story: I loved Whisper of the wicked ...   
8   pos  A FIVE STAR BOOK: I just finished reading Whis...   
9   pos  Whispers of the Wicked Saints: This was a easy...   

                                              scores  compund  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...   0.9454  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...   0.8957  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...   0.9858  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...   0.9814  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...   0.9781  
5  {'neg': 0.014, 'neu': 0.737, 'pos': 0.249, 'co...   0.9900  
6  {'neg': 0.124, 'neu': 0.806, 'pos': 0.069, 'co...  -0.8744  
7  {'neg': 0.072, 'neu': 0.583, 'pos': 0.346, 'co...   0.9900  
8  {'neg': 0.113, 'neu': 0.712, 'pos': 0.174, 'co...   0.8353  
9  {'neg': 0.033, 'neu': 0.777, 'pos': 0.19, 'com...   0.8196

In [113]:
data['comp_score'] = data['compund'].apply(lambda x: 1 if x>=0 else 0)

In [117]:
data['label'] = data['label'].apply(lambda x: 1 if x=='pos' else 0)
data

label                                             review  \
0         1  Stuning even for the non-gamer: This sound tra...   
1         1  The best soundtrack ever to anything.: I'm rea...   
2         1  Amazing!: This soundtrack is my favorite music...   
3         1  Excellent Soundtrack: I truly like this soundt...   
4         1  Remember, Pull Your Jaw Off The Floor After He...   
...     ...                                                ...   
9995      1  A revelation of life in small town America in ...   
9996      1  Great biography of a very interesting journali...   
9997      0  Interesting Subject; Poor Presentation: You'd ...   
9998      0  Don't buy: The box looked used and it is obvio...   
9999      1  Beautiful Pen and Fast Delivery.: The pen was ...   

                                                 scores  compund  comp_score  \
0     {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...   0.9454           1   
1     {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...   0.8957           1   
2     {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...   0.9858           1   
3     {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...   0.9814           1   
4     {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...   0.9781           1   
...                                                 ...      ...         ...   
9995  {'neg': 0.017, 'neu': 0.846, 'pos': 0.136, 'co...   0.9610           1   
9996  {'neg': 0.0, 'neu': 0.868, 'pos': 0.132, 'comp...   0.9544           1   
9997  {'neg': 0.084, 'neu': 0.754, 'pos': 0.162, 'co...   0.9102           1   
9998  {'neg': 0.091, 'neu': 0.909, 'pos': 0.0, 'comp...  -0.3595           0   
9999  {'neg': 0.028, 'neu': 0.811, 'pos': 0.161, 'co...   0.9107           1   

      score_avg  
0        0.0546  
1        0.1043  
2        0.0142  
3        0.0186  
4        0.0219  
...         ...  
9995     0.0380  
9996     0.0456  
9997     0.0898  
9998     1.3595  
9999     0.0893  

[10000 rows x 6 columns]

In [118]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [119]:
confusion_matrix(data['label'],data['comp_score'])

array([[2629, 2468],
       [ 435, 4468]], dtype=int64)

In [120]:
print(classification_report(data['label'],data['comp_score']))

              precision    recall  f1-score   support

           0       0.86      0.52      0.64      5097
           1       0.64      0.91      0.75      4903

    accuracy                           0.71     10000
   macro avg       0.75      0.71      0.70     10000
weighted avg       0.75      0.71      0.70     10000



In [121]:
accuracy_score(data.label,data.comp_score)

0.7097

In [122]:
data['score_avg'] = data['scores'].apply(lambda x: (x['neg']+x['neu']+x['pos'])-x['compound'])

In [123]:
data.head(10)

label                                             review  \
0      1  Stuning even for the non-gamer: This sound tra...   
1      1  The best soundtrack ever to anything.: I'm rea...   
2      1  Amazing!: This soundtrack is my favorite music...   
3      1  Excellent Soundtrack: I truly like this soundt...   
4      1  Remember, Pull Your Jaw Off The Floor After He...   
5      1  an absolute masterpiece: I am quite sure any o...   
6      0  Buyer beware: This is a self-published book, a...   
7      1  Glorious story: I loved Whisper of the wicked ...   
8      1  A FIVE STAR BOOK: I just finished reading Whis...   
9      1  Whispers of the Wicked Saints: This was a easy...   

                                              scores  compund  comp_score  \
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...   0.9454           1   
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...   0.8957           1   
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...   0.9858           1   
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...   0.9814           1   
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...   0.9781           1   
5  {'neg': 0.014, 'neu': 0.737, 'pos': 0.249, 'co...   0.9900           1   
6  {'neg': 0.124, 'neu': 0.806, 'pos': 0.069, 'co...  -0.8744           0   
7  {'neg': 0.072, 'neu': 0.583, 'pos': 0.346, 'co...   0.9900           1   
8  {'neg': 0.113, 'neu': 0.712, 'pos': 0.174, 'co...   0.8353           1   
9  {'neg': 0.033, 'neu': 0.777, 'pos': 0.19, 'com...   0.8196           1   

   score_avg  
0     0.0546  
1     0.1043  
2     0.0142  
3     0.0186  
4     0.0219  
5     0.0100  
6     1.8734  
7     0.0110  
8     0.1637  
9     0.1804

In [124]:
X = data[['compund','comp_score']]
y = data['label']

import sklearn
from sklearn.model_selection import train_test_split

In [125]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

### logistic regression

In [126]:
from sklearn.linear_model import LogisticRegression
lgr_model = LogisticRegression()

In [127]:
lgr_model.fit(X_train,y_train)

LogisticRegression()

In [128]:
predictions = lgr_model.predict(X_test)

In [129]:
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test,predictions))

[[1154  495]
 [ 283 1368]]
              precision    recall  f1-score   support

           0       0.80      0.70      0.75      1649
           1       0.73      0.83      0.78      1651

    accuracy                           0.76      3300
   macro avg       0.77      0.76      0.76      3300
weighted avg       0.77      0.76      0.76      3300

0.7642424242424243


### svm

In [131]:
from sklearn.svm import SVC
svm_model = SVC()
svm_model.fit(X_train, y_train)

SVC()

In [132]:
predictions = svm_model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test,predictions))

[[1193  456]
 [ 338 1313]]
              precision    recall  f1-score   support

           0       0.78      0.72      0.75      1649
           1       0.74      0.80      0.77      1651

    accuracy                           0.76      3300
   macro avg       0.76      0.76      0.76      3300
weighted avg       0.76      0.76      0.76      3300

0.7593939393939394


###  Naive bayes

In [136]:
from sklearn.svm import LinearSVC
nm_model = LinearSVC()
nm_model.fit(X_train, y_train)

LinearSVC()

In [137]:
predictions = svm_model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test,predictions))

[[1193  456]
 [ 338 1313]]
              precision    recall  f1-score   support

           0       0.78      0.72      0.75      1649
           1       0.74      0.80      0.77      1651

    accuracy                           0.76      3300
   macro avg       0.76      0.76      0.76      3300
weighted avg       0.76      0.76      0.76      3300

0.7593939393939394
